POST http://localhost:5144/Desktop/UserToken/Register
content-type: application/json

{
  "UserId": "sampleUserId",
  "Token": "sampleToken"
}
###
POST http://localhost:5144/Desktop/UserToken/Update
content-type: application/json

{
  "UserId": "sampleUserId",
  "Token": "sampleToken"
}
###
POST http://localhost:5144/Mobile/Notification/Handle
content-type: application/json

{
  "UserId": "sampleUserId",
  "NotificationText": "sampleNotificationText"
}