######### Testovaya huinya

GET https://localhost:5001/

###
GET https://localhost:5001/todos/1

###
GET https://localhost:5001/GetContext


###
GET https://localhost:5001/GetDatabase

###
POST https://localhost:5001/todos
content-type: application/json

{ 
  "id":1,  
"name":"aaa",   
"isComplited":true
}

######### User 

POST https://localhost:5001/Mobile/User/Login
content-type: application/json

{
  "UserCred":"myuser",
  "Password": "testuser4testuser4"
}
###
POST https://localhost:5001/Desktop/User/Login
content-type: application/json

{
  "UserCred":"myuser",
  "Password": "testuser4testuser4"
}
###
POST https://localhost:5001/User/Logout
content-type: application/json

{
  "UserCred":"testuser3",
  "Password": "44444123123123"
}

######### UserSettings

GET https://localhost:5001/Desktop/UserSettings/Get/sDAmWae7RqMsmWIC74lVdLuQRpq1
###

POST https://localhost:5001/Desktop/UserSettings/Update
content-type: application/json

{
  "userId": "sDAmWae7RqMsmWIC74lVdLuQRpq1",
  "userName": null,
  "nickname": null,
  "phoneNumber": null,
  "address": null,
  "country": null,
  "about": null,
  "commentsOnArticle": false,
  "answersOnForm": false,
  "onFollower": false,
  "newsAnnouncements": false,
  "productUpdates": false,
  "blogDigest": false,
  "selectedGroup": 1,
  "rowsCount": 100
  
}

######### Account

POST https://localhost:5001/Desktop/Account/Register
content-type: application/json

{
  "UserId": "sDAmWae7RqMsmWIC74lVdLuQRpq1",
  "AccountData": {
    "AccountNumber": "sampleAccountNumber",
    "LastName": "sampleLastName",
    "AccountGroup": 1,
    "DeviceId": 2,
    "SimSlot": 1,
    "SimCardNumber": "+88005553535",
    "BankCardNumber": "1488",
    "BankType": "Sbebank",
    "Description": "sampleDescription"
  }
}
###
POST https://localhost:5001/Desktop/Account/Update
content-type: application/json

{
  "UserId": "sDAmWae7RqMsmWIC74lVdLuQRpq1",
  "AccountId": "53bc6280-1f8c-40b5-88a7-5a0e3e5e3f75",
  "AccountData": {
    "AccountNumber": "sampleAccountNumber3",
    "LastName": "sampleLastName",
    "AccountGroup": 3,
    "DeviceId": 1,
    "SimSlot": 1,
    "SimCardNumber": "+88005553566",
    "BankCardNumber": "1234",
    "BankType": "sampleBankType",
    "Description": "sampleDescription"
  }
}
###
POST https://localhost:5001/Desktop/Account/Delete
content-type: application/json 

{
  "AccountId": "sampleAccountId"
}
###
GET https://localhost:5001/Mobile/Account/GetForDevice/sDAmWae7RqMsmWIC74lVdLuQRpq1/3/3

###
GET https://localhost:5001/Desktop/Account/GetAllForUser/sDAmWae7RqMsmWIC74lVdLuQRpq1

######### UserToken

POST https://localhost:5001/Desktop/UserToken/Set
content-type: application/json

{
  "UserId": "sDAmWae7RqMsmWIC74lVdLuQRpq1",
  "Token": "sampleToken"
}

###
POST https://localhost:5001/Desktop/UserToken/Delete
content-type: application/json

{
  "UserId": "sDAmWae7RqMsmWIC74lVdLuQRpq1"
}

######### Transaction

POST https://localhost:5001/Mobile/Transaction/HandleNew
content-type: application/json

{
  "UserId": "sDAmWae7RqMsmWIC74lVdLuQRpq1",
  "NotificationText": "СЧЁТ2280 16:00 перевод 3900р Комиссия 19.50р Баланс: 69.40р"
}

###
POST https://localhost:5001/Desktop/Transaction/GetMessages
content-type: application/json

{
  "UserId": "sDAmWae7RqMsmWIC74lVdLuQRpq1",
  "SearchText":"",
  "AccountNumber":"123456789",
  "StartingDate":"2024-09-19T00:42:30.647Z",
  "EndingDate":"2024-09-21T00:42:30.647Z",
  "MessageType":-1,
  "Amount":100
}
