######### Testovaya huinya

GET https://localhost:5001/

###
GET https://localhost:5001/GetContext

###
GET https://localhost:5001/GetDatabase

###
POST  https://localhost:5001/Check

###
POST https://localhost:5001/todos
content-type: application/json

{ 
  "id":1,  
"name":"aaa",   
"isComplited":true
}

###
GET https://localhost:5001/GetConnections

######### User 

POST https://localhost:5001/Desktop/User/Register
content-type: application/json

{
   "Email": "my@example.com",
  "DisplayName":"myuser",
  "Password": "testuser4testuser4"
}

###
POST https://localhost:5001/Mobile/User/Login
content-type: application/json

{
  "UserCred":"myuser",
  "Password": "testuser4testuser4"
}
###
POST https://localhost:5001/Desktop/User/Login
content-type: application/json

{
  "UserCred":"myuser",
  "Password": "testuser4testuser4"
}
###
POST https://localhost:5001/User/Logout
content-type: application/json

{
  "UserCred":"testuser3",
  "Password": "44444123123123"
}

######### UserSettings

GET https://localhost:5001/Desktop/UserSettings/Get/sDAmWae7RqMsmWIC74lVdLuQRpq1
###

POST https://localhost:5001/Desktop/UserSettings/Update
content-type: application/json

{
  "userId": "Ex6YYoPzbJhiuAefYYbwNbjQF9k2",
  "userName": null,
  "nickname": null,
  "phoneNumber": null,
  "address": null,
  "country": null,
  "about": null,
  "commentsOnArticle": false,
  "answersOnForm": false,
  "onFollower": false,
  "newsAnnouncements": false,
  "productUpdates": false,
  "blogDigest": false,
  "selectedGroups": [
    2
  ],
  "rowsCount": 100
}

######### Account

POST https://localhost:5001/Desktop/Account/Register
content-type: application/json

{
  "UserId": "Ex6YYoPzbJhiuAefYYbwNbjQF9k2",
  "AccountData": {
    "AccountNumber": "1234",
    "LastName": "asdfsadf",
    "AccountGroup": 1,
    "DeviceId": 1,
    "SimSlot": 1,
    "SimCardNumber": "+1111111111",
    "BankCardNumber": "2222",
    "InitialBalance": "500",
    "BankType": "Sberbank",
    "InitialSmsBalance":"2000",
    "Description": "111111"
  }
}

###
POST https://localhost:5001/Desktop/Account/Update
content-type: application/json

{
  "UserId": "Ex6YYoPzbJhiuAefYYbwNbjQF9k2",
  "AccountId": "0999d646-6f7a-4057-81ef-8ae7e1115e32",
  "AccountData": {
    "AccountNumber": "1234",
    "LastName": "asdfsadf",
    "AccountGroup": 1,
    "DeviceId": 1,
    "SimSlot": 1,
    "SimCardNumber": "+1111111111",
    "BankCardNumber": "2222",
    "InitialBalance": "500",
    "BankType": "Sberbank",
    "InitialSmsBalance":"2000",
    "Description": "111111"
  }
}
###
POST https://localhost:5001/Desktop/Account/Delete
content-type: application/json 

{
  "AccountId": "1c202e1d-9456-43c0-94cb-3df998267277"
}
###
POST https://localhost:5001/Desktop/Account/SetBalance
content-type: application/json

{
  "AccountId": "02ac5ca2-9bdf-4261-80a0-787c3c0c4bc3",
  "Balance":10
}
###
GET https://localhost:5001/Mobile/Account/GetForDevice/Ex6YYoPzbJhiuAefYYbwNbjQF9k2/21/1

###
GET https://localhost:5001/Desktop/Account/GetAllForUser/Ex6YYoPzbJhiuAefYYbwNbjQF9k2

###
GET https://localhost:5001/Desktop/Account/GetAllAccountNameNumberBankForUser/Ex6YYoPzbJhiuAefYYbwNbjQF9k2

######### Transaction

POST https://localhost:5001/Mobile/Transaction/HandleNew
content-type: application/json

{
  "UserId": "Ex6YYoPzbJhiuAefYYbwNbjQF9k2",
  "GroupId": 2,
  "DeviceId": 2,
  "NotificationText": "Выполнен перевод 10000р со счёта *1234. Павел Николаевич М через СБП."
}

###
POST https://localhost:5001/Desktop/Transaction/GetMessages
content-type: application/json

{
  "UserId": "Ex6YYoPzbJhiuAefYYbwNbjQF9k2",
  "SearchText": null,
  "LastName": "Саламатин",
  "SimCard": "+79604917306",
  "BankType": "Sberbank",
  "StartingDate": null,
  "EndingDate": null,
  "MessageType": null,
  "Amount": 100
}

###
POST https://localhost:5001/Desktop/Transaction/CalculateBalance
content-type: application/json

{
"UserId": "Ex6YYoPzbJhiuAefYYbwNbjQF9k2"
}